name: Publicar APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  upload-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4

      - name: Guardar o APK
        uses: actions/upload-artifact@v4
        with:
          name: FlappyBird-APK
          path: "FlappyBird.apk"
